# docker-compose.dev.yml (Surcharge pour le développement local)
services:
  nuxt-app:
    environment:
      - NODE_ENV=development # Surcharge la variable pour le dev
    volumes:
      - ./nuxt-app:/usr/src/app # Ajout du volume pour le Hot Reload
      - /usr/src/app/node_modules # Contournement pour éviter d'écraser node_modules
    
    # Surcharge la commande pour utiliser 'npm run dev'
    # Utilisation d'un entrypoint pour s'assurer que Nuxt dev est bien appelé
    entrypoint: ["npm", "run", "dev"]
    
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_MONGODB_URL=${MONGO_DB_URI}
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
    depends_on:
      - mongodb