# docker-compose.yml (Configuration de base/production)
services:
  nuxt-app:
    build:
      context: ./nuxt-app
      dockerfile: Dockerfile
      args:
        NODE_ENV: production # Utilise l'Ã©tape de production du Dockerfile
        # ðŸš¨ Transmission des variables au BUILD
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        MONGO_DB_NAME: ${MONGO_DB_NAME}
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - NODE_ENV=production # Variable d'environnement pour Nuxt
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
    # Volumes DEV (volumes: - ./nuxt-app:/usr/src/app) SUPPRIMÃ‰S

    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./data/personal-db:/data/db

  caddy:
    image: caddy:latest
    container_name: personal-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - nuxt-app
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: