services:
  personal-nuxt-app:
    build: ./nuxt-app
    container_name: personal-nuxt-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://personal-mongodb:27017
    volumes:
      - ./nuxt-app:/usr/src/app
    depends_on:
      - personal-mongodb

  personal-mongodb:
    image: mongo:latest
    container_name: personal-mongodb
    ports:
      - "27018:27017"
    volumes:
      - ./data/db:/data/db
