# docker-compose.yml (Configuration de base/production)
services:
  nuxt-app:
    build:
      context: ./nuxt-app
      dockerfile: Dockerfile
      args:
        NODE_ENV: production # Utilise l'Ã©tape de production du Dockerfile
        # ðŸš¨ Transmission des variables au BUILD
        MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
        MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
        MONGO_DB_NAME: ${MONGO_DB_NAME}
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production # Variable d'environnement pour Nuxt
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
    # Volumes DEV (volumes: - ./nuxt-app:/usr/src/app) SUPPRIMÃ‰S

    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017" # Peut Ãªtre retirÃ© en production si non exposÃ©
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./data/personal-db:/data/db